import streamlit as st
import networkx as nx
import folium
from streamlit_folium import st_folium
import json
import numpy as np
import os
from tensorflow.keras.models import load_model

# --- PAGE CONFIGURATION ---
st.set_page_config(layout="wide", page_title="Project Sentinel", page_icon="🛡️")

st.title("🛡️ Project Sentinel: Supply Chain Immunity")
st.markdown("Predictive Contagion Engine & Dynamic Network Rerouting")
st.divider()

# --- CACHE THE AI MODEL TO PREVENT RELOAD LAG ---
@st.cache_resource
def get_ai_model():
    if os.path.exists("sentinel_lstm.h5"):
        return load_model("sentinel_lstm.h5", compile=False)
    return None
lstm_model = get_ai_model()

# --- BUILD THE GRAPH ENGINE ---
locations = {
    "Mumbai Port": [18.944, 72.836],
    "Pune Hub": [18.520, 73.856],
    "Nashik Hub": [20.000, 73.780],
    "Surat Factory": [21.170, 72.831],
    "Ahmedabad Plant": [23.022, 72.571]
}

G = nx.Graph()
for node, coords in locations.items():
    G.add_node(node, pos=coords)

edges = [
    ("Mumbai Port", "Pune Hub", 3),
    ("Mumbai Port", "Nashik Hub", 4),
    ("Pune Hub", "Surat Factory", 6),
    ("Nashik Hub", "Surat Factory", 5),
    ("Surat Factory", "Ahmedabad Plant", 4)
]
G.add_weighted_edges_from(edges)

# --- UI LAYOUT: TWO COLUMNS ---
col1, col2 = st.columns([1, 2]) # col1 is narrower, col2 is wider

with col1:
    st.subheader("📡 Live Dark Data Feed")
    
    # Load the JSON data generated by Phase 1
    try:
        with open("live_alerts.json", "r") as file:
            alerts = json.load(file)
            for alert in alerts[:3]: # Show top 3 alerts
                st.info(f"**{alert['location']}**: {alert['raw_text_snippet']}")
    except FileNotFoundError:
        st.warning("Dark Data Pipeline offline. Run `dark_data_pipeline.py` in background.")

    st.subheader("⚙️ System Controls")
    simulation_state = st.radio(
        "Network Status Override:",
        ("🟢 Baseline (Normal Ops)", "🚨 AI ALERT: Severe Disruption at Pune")
    )

# --- AI & GRAPH LOGIC ---
infected = False
if "🚨" in simulation_state:
    infected = True
    
    # Simulate the LSTM predicting a 48-hour delay based on the dark data
    if lstm_model:
        # In a full production app, you would pass real sequence data here.
        # We simulate the AI output for the hackathon demo.
        predicted_delay = 48 
    else:
        predicted_delay = 48
        
    G["Mumbai Port"]["Pune Hub"]['weight'] += predicted_delay
    G["Pune Hub"]["Surat Factory"]['weight'] += predicted_delay
    
    with col1:
        st.error(f"⚠️ **CONTAGION DETECTED**\nLSTM Engine predicts a {predicted_delay}-hour delay at Pune Hub.")
        st.success("✅ **SENTINEL ACTIVE**\nGraph weights dynamically updated. Rerouting via Nashik.")

# Calculate the optimal path
path = nx.shortest_path(G, source="Mumbai Port", target="Ahmedabad Plant", weight="weight")
transit_time = nx.shortest_path_length(G, source="Mumbai Port", target="Ahmedabad Plant", weight="weight")

with col1:
    st.metric(label="Estimated Transit Time (Hours)", value=transit_time)

# --- MAP RENDERING ---
with col2:
    # Center map on Western India
    m = folium.Map(location=[20.5937, 72.9629], zoom_start=6)

    # Draw the active route in green
    for i in range(len(path)-1):
        start_node = path[i]
        end_node = path[i+1]
        folium.PolyLine([locations[start_node], locations[end_node]], color="#00ff00", weight=5).add_to(m)

    # Draw nodes and handle infection highlighting
    for node, coords in locations.items():
        if infected and node == "Pune Hub":
            folium.Marker(coords, popup="🚨 COMPROMISED NODE", icon=folium.Icon(color="red", icon="warning")).add_to(m)
            # Add a red circle to show the "blast radius"
            folium.CircleMarker(coords, radius=30, color="red", fill=True, fill_color="red", fill_opacity=0.3).add_to(m)
        elif node in path:
            folium.Marker(coords, popup=node, icon=folium.Icon(color="green", icon="check")).add_to(m)
        else:
            folium.Marker(coords, popup=node, icon=folium.Icon(color="blue", icon="info-sign")).add_to(m)

    st_folium(m, width=800, height=500)